### ISSUE TITLE
The yml workflow is giving errors

### ISSUE THREAD

**Issue by the1Riddle** [Hezethegamer/testing#343]
<h1>Error starting the game.</h1>

previously when you started a new game, it returned 0
but correctly it throws some errors.

> [!WARNING]\
> **Play Chess**
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-> python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by the1Riddle** [comment]
some good option might be to revert the commit to the prev one

or update it.

**Comment by Hezethegamer** [comment]
**Making some FIX**

made some few changes, check it out if it works....

**Comment by the1Riddle** [comment]
> **Making some FIX**
> 
> made some few changes, check it out if it works....

Still not working,

***`The main problem here is not using a depreciated nodejs`***
the problem is using incompatible node js > _thats what I see here_

**Comment by Hezethegamer** [comment]
let me see what i can do about that...

**Comment by the1Riddle** [comment]
update, according to [this blog](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)

All Actions will run on Node20 instead of Node16 by default

**Comment by the1Riddle** [comment]
#405 enhansment complete

**Comment by Hezethegamer** [comment]
ok
